# Generated by Django 6.0 on 2025-12-26 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'blood_type',
            },
        ),
        migrations.CreateModel(
            name='AuditLogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField()),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_log',
            },
        ),
        migrations.CreateModel(
            name='BloodUnitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('available', 'Còn trong kho'), ('reserved', 'Đã giữ cho yêu cầu'), ('used', 'Đã sử dụng'), ('expired', 'Hết hạn sử dụng')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blood_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure_app.bloodtypemodel')),
            ],
            options={
                'db_table': 'blood_unit',
            },
        ),
        migrations.CreateModel(
            name='DonorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Nam'), ('female', 'Nữ'), ('other', 'Khác')], max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blood_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='infrastructure_app.bloodtypemodel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'donor',
            },
        ),
        migrations.CreateModel(
            name='DonationEventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('blood_unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='infrastructure_app.bloodunitmodel')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure_app.donormodel')),
            ],
            options={
                'db_table': 'donation_event',
            },
        ),
        migrations.AddField(
            model_name='bloodunitmodel',
            name='donor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='infrastructure_app.donormodel'),
        ),
        migrations.CreateModel(
            name='HospitalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hospital',
            },
        ),
        migrations.CreateModel(
            name='BloodRequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đẫ duyệt'), ('rejected', 'Từ chối'), ('completed', 'Hoàn tất')], max_length=20)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('blood_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='infrastructure_app.bloodtypemodel')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure_app.hospitalmodel')),
            ],
            options={
                'db_table': 'blood_request',
            },
        ),
    ]
